INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (1,NULL,1,'Dashboard','','',1,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (2,NULL,2,'Penjualan','','',2,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (3,NULL,3,'Pembelian','','',3,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (4,NULL,4,'Inventory','','',4,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (5,NULL,5,'Workorder','','',5,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (6,NULL,6,'Finance','','',6,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (7,NULL,7,'Laporan','','',7,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (8,NULL,8,'Partnership','','',8,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (9,NULL,9,'Pengaturan','','',9,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (10,2,11,'Sales Order','','',1,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (11,2,12,'Sales Invoice','','',2,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (12,2,13,'Sales Return','','',3,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (13,3,14,'Purchase Order','','',1,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (14,3,15,'Purchase Invoice','','',2,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (15,3,16,'Purchase Return','','',3,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (16,4,17,'Daftar Item','','',1,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (17,4,20,'Direct Placement','','',2,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (18,4,21,'Stock Opname','','',3,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (19,5,22,'Fulfillment','','',1,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (20,5,23,'Shipment','','',2,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (21,5,24,'Receiving','','',3,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (22,6,25,'Pendapatan','','',1,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (23,6,26,'Pengeluaran','','',2,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (24,6,27,'Tanda Terima Invoice','','',3,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (25,7,28,'Penjualan','','',1,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (26,7,29,'Pembelian','','',2,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (27,7,30,'Penjualan Item','','',3,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (28,7,31,'Pembelian Item','','',4,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (29,7,32,'Utang','','',5,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (30,7,33,'Piutang','','',6,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (31,7,34,'Penjualan Customer','','',7,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (32,9,35,'Aplikasi','','',1,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (33,9,36,'Tipe Harga','','',2,1);
INSERT INTO `application_menu` (`id`,`parent_menu_id`,`application_module_id`,`menu_name`,`icon`,`route`,`order`,`is_active`) VALUES (34,9,37,'Pengguna','','',3,1);
