SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS `item_category` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `note` TINYTEXT NULL DEFAULT NULL,
  `is_deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
